version: '3.8'

services:
  db:
    image: postgres:16.2-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: workout
      TZ: America/Bogota
    volumes:
      - ./postgres-data:/var/postgresql/data
    networks:
      - custom_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
